# Generated by Django 3.0.3 on 2020-05-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='coupon_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
