# Generated by Django 3.0.3 on 2020-05-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_auto_20200509_2148'),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_products',
            field=models.ManyToManyField(null=True, to='Products.Product'),
        ),
    ]
