# Generated by Django 3.0.3 on 2020-04-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
