# Generated by Django 3.0.3 on 2020-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20200321_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='tracking_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
