# Generated by Django 3.0.3 on 2020-04-10 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0015_auto_20200414_0937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('started', 'Started'), ('abandoned', 'Abandoned'), ('finished', 'Finished')], default='submitted', max_length=120)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('shipping_first_name', models.CharField(max_length=50, null=True)),
                ('shipping_last_name', models.CharField(max_length=50, null=True)),
                ('shipping_address_1', models.CharField(max_length=50, null=True)),
                ('shipping_address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_city', models.CharField(max_length=50, null=True)),
                ('shipping_state', models.CharField(max_length=2, null=True)),
                ('shipping_country', models.CharField(max_length=50, null=True)),
                ('shipping_zip', models.CharField(max_length=10, null=True)),
                ('billing_first_name', models.CharField(max_length=50, null=True)),
                ('billing_last_name', models.CharField(max_length=50, null=True)),
                ('billing_address_1', models.CharField(max_length=50, null=True)),
                ('billing_address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_city', models.CharField(max_length=50, null=True)),
                ('billing_state', models.CharField(max_length=2, null=True)),
                ('billing_country', models.CharField(max_length=50, null=True)),
                ('billing_zip', models.CharField(max_length=10, null=True)),
                ('billing_other_note', models.TextField(null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Carts.Carts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
    ]
