# Generated by Django 3.0.6 on 2020-05-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_zip',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_different_address',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_first_name', models.CharField(max_length=50, null=True)),
                ('shipping_last_name', models.CharField(max_length=50, null=True)),
                ('shipping_address_1', models.CharField(max_length=50, null=True)),
                ('shipping_address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_city', models.CharField(max_length=50, null=True)),
                ('shipping_state', models.CharField(max_length=2, null=True)),
                ('shipping_country', models.CharField(max_length=50, null=True)),
                ('shipping_zip', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Order')),
            ],
        ),
    ]
