# Generated by Django 3.0.3 on 2020-03-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('other_notes', models.TextField(max_length=220)),
                ('normal_price', models.DecimalField(decimal_places=2, default=6500, max_digits=100)),
                ('sale_price', models.DecimalField(decimal_places=2, default=6500, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vlisco', 'VLISCO'), ('chiganvy', 'CHYGANVY'), ('hollandais', 'HOLLANDAIS'), ('hitarger', 'HITARGET')], default='vlisco', max_length=120)),
                ('product_title', models.CharField(max_length=128)),
                ('product_color', models.CharField(max_length=128)),
                ('product_theme_color', models.CharField(max_length=128)),
                ('product_theme_writing', models.CharField(blank=True, max_length=228, null=True)),
                ('product_reference', models.TextField()),
                ('product_origin_country', models.CharField(blank=True, max_length=128, null=True)),
                ('production_year', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('thumbnails', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.ProductCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'slug')},
        ),
    ]
