# Generated by Django 3.0.3 on 2020-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(null=True, to='Products.ProductImage'),
        ),
    ]
