# Generated by Django 3.0.3 on 2020-03-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200323_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('vlisco', 'VLISCO'), ('chiganvy', 'CHYGANVY'), ('hollandais', 'HOLLANDAIS'), ('hitarger', 'HITARGET'), ('heritage_by_sunshine', 'HERITAGE BY SUNSHINE'), ('metro', 'METRO'), ('wax', 'WAX'), ('so_special', 'SO SPECIAL')], default='vlisco', max_length=120),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
