# Generated by Django 3.0.3 on 2020-03-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20200324_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
