# Generated by Django 3.0.3 on 2020-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200327_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='production_year',
            field=models.DateField(),
        ),
    ]
