# Generated by Django 3.0.3 on 2020-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20200327_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('vlisco', 'VLISCO'), ('chiganvy', 'CHYGANVY'), ('hollandais', 'HOLLANDAIS'), ('hitarger', 'HITARGET'), ('heritage_by_sunshine', 'HERITAGE BY SUNSHINE'), ('metro', 'METRO'), ('wax', 'WAX'), ('so_special', 'SO SPECIAL'), ('sejection', 'SEJECTION')], default='vlisco', max_length=120),
        ),
    ]
