# Generated by Django 3.0.3 on 2020-04-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20200413_0939'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
