# Generated by Django 3.0.3 on 2020-05-06 22:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20200327_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('other_notes', models.TextField(max_length=220)),
                ('normal_price', models.DecimalField(decimal_places=2, default=6500, max_digits=100)),
                ('sale_price', models.DecimalField(decimal_places=2, default=6500, max_digits=100)),
                ('quantity_in_stock', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('views', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=datetime.datetime(2020, 5, 6, 22, 22, 32, 116187, tzinfo=utc))),
                ('valid_to', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.ProductCategory')),
                ('images', models.ManyToManyField(to='Products.ProductImage')),
            ],
        ),
    ]
