# Generated by Django 3.0.3 on 2020-05-09 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_dealoftheweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealoftheweek',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 20, 48, 43, 792967, tzinfo=utc)),
        ),
    ]
